.Dd February 20, 2020
.Dt CHECKRESTART 1
.Os
.Sh NAME
.Nm checkrestart
.Nd check for processes that may need restarting
.Sh SYNOPSIS
.Nm
.Op Fl Hb
.Op Ar pid ...
.Sh DESCRIPTION
The
.Nm
command searches for processes without associated executable or library paths,
implying a software upgrade has replaced them since it was started.
.Pp
.Nm
does not perform any system changes itself - it is strictly informational.
It is the responsibility of the system administrator to interpret the results
and take any necessary action.
.Pp
For system-wide checks,
.Nm
should be executed as the superuser to allow it access to global virtual memory
mappings.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl H
Suppress the header.
.It Fl b
Check only for missing binaries, skipping the far more expensive check for stale
libraries.
.El
.Sh EXAMPLES
.Bd -literal -offset indent
 # checkrestart
  PID   JID         COMMAND UPDATED ARGS
44960     0         weechat Library /usr/local/bin/weechat
81345     0            tmux  Binary tmux: server (/tmp/tmux-1001/default)
80307     0            tmux  Binary tmux: client (/tmp/tmux-1001/default)
18115     1       memcached  Binary /usr/local/bin/memcached
.Ed
.Pp
This output indicates
.Nm weechat
is using an out of date library, a
.Nm tmux
client/server pair is using an out-of-date executable, having replaced its
arguments list obscuring its location, and
.Nm memcached
, running in Jail 1, is also out of date having left its arguments list as the
full path to its original executable.
.Sh HISTORY
A
.Nm
command first appeared in the debian-extras package in Debian Linux.
.Pp
This
.Nm
implementation performs a similar, but not identical task, and takes the name
because why not.
.Sh AUTHORS
.An Thomas Hurst Aq tom@hur.st
.Sh BUGS
.Nm
may report false-positives due to VFS name cache evictions, though this has not
yet been observed by the author.
