.Dd February 21, 2020
.Dt CHECKRESTART 1
.Os
.Sh NAME
.Nm checkrestart
.Nd check for processes that may need restarting
.Sh SYNOPSIS
.Nm
.Op Fl -libxo
.Op Fl bHw
.Op Fl j Ar jail
.Op Fl u Ar user
.Op Ar proc ...
.Sh DESCRIPTION
The
.Nm
command attempts to find processes that need restarting following a software
upgrade, as indicated by their underlying executable or shared libraries no
longer appearing on disk.
.Pp
.Nm
does not perform any system changes itself \(em it is strictly informational and
best-effort (See the
.Sx BUGS
section).
It is the responsibility of the system administrator to interpret the results
and take any necessary action.
.Pp
For full system-wide checks,
.Nm
should be executed as the superuser to allow it access to global virtual memory
mappings.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl -libxo
Generate formatted output via
.Xr libxo 3
in a selection of human and machine-readable formats.
See
.Xr xo_parse_args 3
for details on available arguments.
.It Fl b
Check only for missing binaries, skipping the far more expensive check for stale
libraries.
.It Fl H
Suppress the header.
.It Fl w
Print the full width of the ARGUMENTS column even if it will wrap in the terminal.
.It Fl j Ar jail
Filter output by specified jail name or ID.
.It Fl u Ar user
Filter output by specified user name or ID.
.El
.Pp
If any
.Ar proc
operands are specified, they are treated as process names, IDs, and group IDs to
limit checks to.
.Sh EXAMPLES
Check all processes visible by the user:
.Bd -literal -offset indent
 # checkrestart
  PID   JID USER         COMMAND      WHY ARGUMENTS
44960     0 freaky       weechat      lib /usr/local/bin/weechat
81345     0 freaky       tmux         bin tmux: server (/tmp/tmux-1001/default)
80307     0 freaky       tmux         bin tmux: client (/tmp/tmux-1001/default)
18115     1 nobody       memcached    bin /usr/local/bin/memcached
.Ed
.Pp
This output indicates
.Nm weechat
is using an out of date library, a
.Nm tmux
client/server pair is using an out-of-date executable, having replaced its
arguments list obscuring its location, and
.Nm memcached ,
running in jail 1, is also out of date having left its arguments list as the
full path to its original executable.
.Pp
Check only processes named weechat and tmux:
.Bd -literal -offset indent
 # checkrestart weechat tmux
.Ed
.Pp
Check only processes with PID 142 and 157:
.Bd -literal -offset indent
 # checkrestart 142 157
.Ed
.Pp
Check only processes in PGID 117:
.Bd -literal -offset indent
 # checkrestart -- -117
.Ed
.Sh SEE ALSO
.Xr procstat 1 ,
.Xr libxo 3 ,
.Xr xo_parse_args 3 ,
.Xr jail 8 ,
.Xr service 8
.Sh HISTORY
A
.Nm
command first appeared in the debian-extras package in Debian Linux.
.Pp
This implementation follows a similar idea, and is based on a prior version
in the author's
.Nm pkg-cruft
Ruby script.
.Pp
An unrelated but similar
.Nm
command is also available as an
.Ox
port.
.Sh AUTHORS
.An Thomas Hurst Aq tom@hur.st
.Sh BUGS
.Nm
may report both false positives and false negatives, depending on program and
kernel behaviour, and should be considered strictly "best-effort".
.Pp
In particular, retrieval of pathnames is implemented using the kernel's name
cache \(em if an executable or library path is not in the name cache due to
an eviction, or use of a file system which does not use the name cache,
.Nm
will consider this the same as if a file is missing.
.Pp
The use of the name cache also means it is not yet possible to report which
files are considered missing.
